import { Job } from "@jobquest/models";

export const GUEST_JOBS: Job[] = [
  {
    id: "1",
    job_title: "Frontend Developer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "Acme Corp",
    posting_date: "2024-01-01",
  },
  {
    id: "2",
    job_title: "UI/UX Designer",
    location: "New York",
    category: "design",
    job_type: "Part Time",
    company_name: "Design Studio",
    posting_date: "2024-02-15",
  },
  {
    id: "3",
    job_title: "Backend Developer",
    location: "San Francisco",
    category: "development",
    job_type: "Full Time",
    company_name: "Techify",
    posting_date: "2024-03-01",
  },
  {
    id: "4",
    job_title: "Full Stack Developer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "CodeWorks",
    posting_date: "2024-03-05",
  },
  {
    id: "5",
    job_title: "Product Manager",
    location: "London",
    category: "management",
    job_type: "Full Time",
    company_name: "Innovate Ltd",
    posting_date: "2024-03-10",
  },
  {
    id: "6",
    job_title: "Graphic Designer",
    location: "Berlin",
    category: "design",
    job_type: "Contract",
    company_name: "Creative Minds",
    posting_date: "2024-03-12",
  },
  {
    id: "7",
    job_title: "Mobile App Developer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "Appify",
    posting_date: "2024-03-15",
  },
  {
    id: "8",
    job_title: "Data Analyst",
    location: "Toronto",
    category: "data",
    job_type: "Full Time",
    company_name: "DataCorp",
    posting_date: "2024-03-18",
  },
  {
    id: "9",
    job_title: "DevOps Engineer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "CloudNet",
    posting_date: "2024-03-20",
  },
  {
    id: "10",
    job_title: "QA Engineer",
    location: "Austin",
    category: "testing",
    job_type: "Full Time",
    company_name: "QualitySoft",
    posting_date: "2024-03-22",
  },
  {
    id: "11",
    job_title: "Marketing Specialist",
    location: "Dubai",
    category: "marketing",
    job_type: "Part Time",
    company_name: "MarketPro",
    posting_date: "2024-03-25",
  },
  {
    id: "12",
    job_title: "SEO Expert",
    location: "Remote",
    category: "marketing",
    job_type: "Contract",
    company_name: "RankBoost",
    posting_date: "2024-03-27",
  },
  {
    id: "13",
    job_title: "Content Writer",
    location: "Remote",
    category: "content",
    job_type: "Part Time",
    company_name: "WriteWell",
    posting_date: "2024-03-29",
  },
  {
    id: "14",
    job_title: "HR Manager",
    location: "Chicago",
    category: "management",
    job_type: "Full Time",
    company_name: "PeopleFirst",
    posting_date: "2024-04-01",
  },
  {
    id: "15",
    job_title: "Business Analyst",
    location: "Boston",
    category: "business",
    job_type: "Full Time",
    company_name: "BizGroup",
    posting_date: "2024-04-03",
  },
  {
    id: "16",
    job_title: "AI Engineer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "AI Labs",
    posting_date: "2024-04-05",
  },
  {
    id: "17",
    job_title: "Machine Learning Engineer",
    location: "Seattle",
    category: "data",
    job_type: "Full Time",
    company_name: "DeepTech",
    posting_date: "2024-04-07",
  },
  {
    id: "18",
    job_title: "Cybersecurity Analyst",
    location: "Washington",
    category: "security",
    job_type: "Full Time",
    company_name: "SecureNet",
    posting_date: "2024-04-09",
  },
  {
    id: "19",
    job_title: "Cloud Engineer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "SkyCloud",
    posting_date: "2024-04-11",
  },
  {
    id: "20",
    job_title: "Game Developer",
    location: "Tokyo",
    category: "development",
    job_type: "Full Time",
    company_name: "GameForge",
    posting_date: "2024-04-13",
  },
  {
    id: "21",
    job_title: "Technical Support Engineer",
    location: "Remote",
    category: "support",
    job_type: "Full Time",
    company_name: "HelpDesk Co",
    posting_date: "2024-04-15",
  },
  {
    id: "22",
    job_title: "Network Engineer",
    location: "Sydney",
    category: "network",
    job_type: "Full Time",
    company_name: "NetSolutions",
    posting_date: "2024-04-17",
  },
  {
    id: "23",
    job_title: "Systems Administrator",
    location: "Remote",
    category: "IT",
    job_type: "Full Time",
    company_name: "SysAdmin Inc",
    posting_date: "2024-04-19",
  },
  {
    id: "24",
    job_title: "UI Developer",
    location: "San Diego",
    category: "development",
    job_type: "Full Time",
    company_name: "DesignTech",
    posting_date: "2024-04-21",
  },
  {
    id: "25",
    job_title: "Digital Marketing Manager",
    location: "Remote",
    category: "marketing",
    job_type: "Full Time",
    company_name: "AdWave",
    posting_date: "2024-04-23",
  },
  {
    id: "26",
    job_title: "Social Media Manager",
    location: "Los Angeles",
    category: "marketing",
    job_type: "Part Time",
    company_name: "SocialBuzz",
    posting_date: "2024-04-25",
  },
  {
    id: "27",
    job_title: "Copywriter",
    location: "Remote",
    category: "content",
    job_type: "Contract",
    company_name: "CopyCraft",
    posting_date: "2024-04-27",
  },
  {
    id: "28",
    job_title: "Video Editor",
    location: "Mumbai",
    category: "media",
    job_type: "Full Time",
    company_name: "MediaHouse",
    posting_date: "2024-04-29",
  },
  {
    id: "29",
    job_title: "Animator",
    location: "Remote",
    category: "design",
    job_type: "Contract",
    company_name: "Animatrix",
    posting_date: "2024-05-01",
  },
  {
    id: "30",
    job_title: "3D Artist",
    location: "Paris",
    category: "design",
    job_type: "Full Time",
    company_name: "VisualWorks",
    posting_date: "2024-05-03",
  },
  {
    id: "31",
    job_title: "Blockchain Developer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "ChainTech",
    posting_date: "2024-05-05",
  },
  {
    id: "32",
    job_title: "AR/VR Developer",
    location: "Remote",
    category: "development",
    job_type: "Full Time",
    company_name: "Immersive Labs",
    posting_date: "2024-05-07",
  },
  {
    id: "33",
    job_title: "Technical Writer",
    location: "Remote",
    category: "content",
    job_type: "Full Time",
    company_name: "DocuTech",
    posting_date: "2024-05-09",
  },
  {
    id: "34",
    job_title: "Sales Manager",
    location: "Delhi",
    category: "sales",
    job_type: "Full Time",
    company_name: "SalesForceX",
    posting_date: "2024-05-11",
  },
  {
    id: "35",
    job_title: "Accountant",
    location: "London",
    category: "finance",
    job_type: "Full Time",
    company_name: "FinancePro",
    posting_date: "2024-05-13",
  },
  {
    id: "36",
    job_title: "Financial Analyst",
    location: "New York",
    category: "finance",
    job_type: "Full Time",
    company_name: "WallStreet Inc",
    posting_date: "2024-05-15",
  },
  {
    id: "37",
    job_title: "Customer Success Manager",
    location: "Remote",
    category: "support",
    job_type: "Full Time",
    company_name: "ClientFirst",
    posting_date: "2024-05-17",
  },
  {
    id: "38",
    job_title: "Operations Manager",
    location: "Singapore",
    category: "management",
    job_type: "Full Time",
    company_name: "OpsGlobal",
    posting_date: "2024-05-19",
  },
  {
    id: "39",
    job_title: "Recruiter",
    location: "Remote",
    category: "HR",
    job_type: "Part Time",
    company_name: "HireFast",
    posting_date: "2024-05-21",
  },
  {
    id: "40",
    job_title: "Legal Advisor",
    location: "Dubai",
    category: "legal",
    job_type: "Full Time",
    company_name: "LawBridge",
    posting_date: "2024-05-23",
  },
  {
    id: "41",
    job_title: "Research Analyst",
    location: "Remote",
    category: "research",
    job_type: "Full Time",
    company_name: "Insight Labs",
    posting_date: "2024-05-25",
  },
  {
    id: "42",
    job_title: "Event Manager",
    location: "Bangkok",
    category: "management",
    job_type: "Contract",
    company_name: "Eventify",
    posting_date: "2024-05-27",
  },
  {
    id: "43",
    job_title: "Photographer",
    location: "Istanbul",
    category: "media",
    job_type: "Contract",
    company_name: "PhotoPro",
    posting_date: "2024-05-29",
  },
  {
    id: "44",
    job_title: "Translator",
    location: "Remote",
    category: "language",
    job_type: "Part Time",
    company_name: "LinguaTech",
    posting_date: "2024-05-31",
  },
  {
    id: "45",
    job_title: "Customer Support Executive",
    location: "Remote",
    category: "support",
    job_type: "Full Time",
    company_name: "SupportHub",
    posting_date: "2024-06-02",
  },
];
